# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.11.0"
require 'xcodeproj'

default_platform :ios

platform :ios do

# Put in Lanes here!
 lane :newApp do
    produce(
        username: 'my.email@gmail.com', # Your iTunes ID
        app_identifier: 'YOUR.BUNDLE.ID', # Your App Bundle ID
        app_name: 'MyApp', # Your App Name
        language: 'English',
        app_version: '1.0',
        sku: '123',
        team_name: 'Your Name' # only necessary when in multiple teams
      )

    # Post to Slack
    slack(
      message: "Created new App!"
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    # Fetch and Create Profiles
    match

    # Retrieve App Name and ID from environment
    name = ENV['CUSTOM_APP_NAME']
    app_id = ENV['CUSTOM_APP_ID']
    team_id = ENV['CUSTOM_TEAM_ID']

    xcodeprojpath = "../platforms/ios/" + name + ".xcodeproj"

    # Update Code Signing
    update_project_codesigning(path: xcodeprojpath, use_automatic_signing: false, team_id: team_id)

    # Patch Project Settings
    proj = Xcodeproj::Project.open("../" + xcodeprojpath)

    proj.build_configurations.each do |item|
        item.build_settings['DEVELOPMENT_TEAM'] = team_id
        item.build_settings['CODE_SIGN_IDENTITY[sdk=iphoneos*]'] = "iPhone Developer"
        item.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = "match AppStore " + app_id
    end

    proj.recreate_user_schemes
    proj.save
    # End of Patching Project Settings

    increment_build_number({
      build_number: latest_testflight_build_number + 1,
      xcodeproj: xcodeprojpath
    })

    # Build the IPA
    gym

    # Upload the IPA to Testflight
    testflight(
       skip_waiting_for_build_processing: true,
       ipa: "./build/MyApp.ipa"
    )

    # Post to Slack
    slack(
      message: "Successfully Upload " + name + " to ITC Testflight",
      default_payloads: [:git_branch, :last_git_commit_message]
    )
  end
end
